/*
Files inside /app uses server rendering by default.
However, useState() only works on client rendering.
Thus it is required to specify "use client";.
*/
"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useState } from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Check if state remains the same among during page navigations.
  const [count, setCount] = useState(0);

  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Root Directory Header</h1>

        <button onClick={() => setCount(count + 1)}>+</button>
        <div>{count}</div>

        {children}
      </body>
    </html>
  );
}
