import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import profileImg from "../public/me.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  // State for toggling dark mode
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rhina Kim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 md:px-20 lg:px-40 bg-white dark:bg-gray-900">
        <section className="min-h-screen">
          {/* --------------- Navbar --------------- */}
          <nav className="flex justify-between py-10 mb-12 dark:text-white">
            {/* ---- Brand Logo ---- */}
            <h1 className="font-burtons text-xl">developedbyed</h1>
            {/* ---- Nav Lists ---- */}
            <ul className="flex items-center">
              {/* Dark / Light Theme Button */}
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)} // toggle
                  className="text-2xl cursor-pointer"
                />
              </li>
              {/* Download Resume Button */}
              <li>
                <a
                  className="px-4 py-2 ml-8 text-white rounded-md border-none
                    bg-gradient-to-r from-cyan-500 to-teal-500" // gradient background
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* --------------- Hero Section --------------- */}
          <div className="p-10 text-center">
            {/* Name */}
            <h2 className="py-2 font-medium text-5xl md:text-6xl text-teal-600 dark:text-teal-400">
              Rhina Kim
            </h2>
            {/* Role */}
            <h3 className="py-2 text-2xl md:text-3xl dark:text-white">
              Developer and designer.
            </h3>
            {/* Description */}
            <p className="max-w-xl mx-auto py-5 text-md md:text-xl leading-8 text-gray-800 dark:text-gray-200">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            {/* Social Icons */}
            <div className="flex justify-center gap-16 py-3 text-5xl text-gray-600 dark:text-gray-400">
              <AiFillLinkedin />
              <AiFillInstagram />
              <AiFillTwitterCircle />
            </div>
            {/* Profile Image */}
            <div
              className="relative w-80 h-80 md:w-96 md:h-96 mx-auto mt-20 rounded-full overflow-hidden
                bg-gradient-to-b from-teal-500" // background gradient
            >
              <Image src={profileImg} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>

        {/* --------------- Business Section --------------- */}
        <section>
          {/* ---- Texts ---- */}
          <div>
            <h3 className="py-1 text-3xl dark:text-white">Services I offer</h3>
            <p className="py-2 text-md leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="py-2 text-md leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          {/* ---- Cards ---- */}
          <div className="lg:flex gap-10">
            {/* Card 1 */}
            <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xl dark:bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-gray-800">Photoshop</p>
              <p className="py-1 text-gray-800">Illustrator</p>
              <p className="py-1 text-gray-800">Figma</p>
              <p className="py-1 text-gray-800">Indesign</p>
            </div>
            {/* Card 2 */}
            <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xl dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-gray-800">Photoshop</p>
              <p className="py-1 text-gray-800">Illustrator</p>
              <p className="py-1 text-gray-800">Figma</p>
              <p className="py-1 text-gray-800">Indesign</p>
            </div>
            {/* Card 3 */}
            <div className="flex-1 p-10 my-10 text-center shadow-lg rounded-xl dark:bg-white">
              <Image src={consulting} width={100} height={100} />
              <h3 className="pt-8 pb-2 text-lg font-medium">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="py-1 text-gray-800">Photoshop</p>
              <p className="py-1 text-gray-800">Illustrator</p>
              <p className="py-1 text-gray-800">Figma</p>
              <p className="py-1 text-gray-800">Indesign</p>
            </div>
          </div>
        </section>

        {/* --------------- Projects Section --------------- */}
        <section className="py-10">
          {/* ---- Texts ---- */}
          <div>
            <h3 className="py-1 text-3xl dark:text-white ">Portofolio</h3>
            <p className="py-2 text-md leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="py-2 text-md leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          {/* ---- Projects ---- */}
          <div className="flex flex-col lg:flex-row lg:flex-wrap gap-10 py-10">
            {/* Project 1 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            {/* Project 2 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            {/* Project 3 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            {/* Project 4 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            {/* Project 5 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            {/* Project 6 */}
            <div className="flex-1 basis-1/3">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
